# #####################################################################
# Automatically generated by qmake (2.01a) mar. sept. 29 22:27:56 2009
# #####################################################################
TEMPLATE = app
TARGET = webdownloader
DEPENDPATH += .
INCLUDEPATH += .
DESTDIR = ../bin
QT += network

# Input
HEADERS += HttpDown.h \
    WebDownloader.h
SOURCES += HttpDown.cpp \
    main.cpp \
    WebDownloader.cpp

TRANSLATIONS = webdownloader_en.ts
